INCLUDE(SimFind)

SIM_FIND(Spacenav 
  RELEASELIBNAMES spnav
  DEBUGLIBNAMES spnav                   
  INCLUDEFILE spnav.h
  INCLUDE_DIR_SUFFIXES include
  LIB_DIR_SUFFIXES lib
  NO_PKGCONFIG)

IF(Spacenav_FOUND)
  ADD_DEFINITIONS(-DHAVE_SPACENAV_LIB)
ENDIF(Spacenav_FOUND)
